### ISSUE TITLE
Crime / Car Success displays wrong number

### ISSUE THREAD

**Issue by alpturedi** [OmertaBeyond/OBv2#148]
Since now they added another line on the work experience. Crime success for instance divides bust out to crime success. Both car and crime stats are erroneous right now.

**Comment by alpturedi** [comment]
`// car
			var carAttempts = parseInt($('table.thinline:eq(5)>tbody>tr:eq(4)>td:last').text().replace(',', ''), 10);
			var successCars = parseInt(getV('carSuccess', 0), 10);
			if (successCars >= 1) {
				var successRate = (successCars / carAttempts) * 100;
				var earned = getV('carMoney', 0);
				var newText = '<tr><td><b>Car nicking success</b></td><td>' + successCars + ' (' + successRate.toFixed(2) + '%, $' + commafy(earned) + ')</td></tr>';
				$('table.thinline:eq(5)>tbody>tr:eq(3)').after(newText);
			}

			// crime stats
			var crimeAttempts = parseInt($('table.thinline:eq(5)>tbody>tr:eq(3)>td:last').text().replace(',', ''), 10);
			var successCrimes = parseInt(getV('crimeSuccess', 0), 10);
			if (successCrimes >= 1) {
				var successRate = (successCrimes / crimeAttempts) * 100;
				var earned = getV('crimeMoney', 0);
				var newText = '<tr><td><b>Crime success</b></td><td>' + successCrimes + ' (' + successRate.toFixed(2) + '%, $' + commafy(earned) + ')</td></tr>';
				$('table.thinline:eq(5)>tbody>tr:eq(2)').after(newText);
			}`

Just increasing selector's second eq seems to fix it.

**Comment by Baelor** [comment]
Looks like this fix was applied in #144, but I forgot to push a release. Will do that today, thanks @alpturedi.

**Comment by alpturedi** [comment]
Closing this than thanks
