### ISSUE TITLE
How to check source

### ISSUE THREAD

**Issue by sencer07** [OmertaBeyond/OBv2#155]
Hi pls help me how to check sources ? i install nodejs and grunt

**Comment by Baelor** [comment]
I'm not sure I fully understand, but `ob.user.js` contains the source code for the user script.

General instructions for installing/usage can be found [here](https://news.omertabeyond.net/addon).

**Comment by sencer07** [comment]
> I'm not sure I fully understand, but `ob.user.js` contains the source code for the user script.
> 
> General instructions for installing/usage can be found [here](https://news.omertabeyond.net/addon).

Thanks :))
