### ISSUE TITLE
OB not selecting all units of booze or narcs

### ISSUE THREAD

**Issue by clammier** [OmertaBeyond/OBv2#37]
Game version: .dm 5.1
Browser: Google Chrome 36.0.1985.125 m
OB version: 2.0.44

I haven't been able to save a source of page, as advised, but once I run into it again and don't forget about it, I'll make sure to do so.

Anyway, the issue is happening when I get a lot of booze or narcs in a heist, every single time so far (it happened at least 4 times, if not more), OB leaves one unit of something out of the equation (it doesn't always seem to be same type). At first I thought it might be related to the fact that selling price is too low in that city, but considering all stuff were quite low, figured that's not the case.

As soon as I'm able to re-create the issue, I'll update it with needed information.

**Comment by Baelor** [comment]
I believe this was fixed in 64e9c4b84bba4b29b56a30cf21410919eb635e8e. Please re-open if you run into this issue again.
