### ISSUE TITLE
Slotstracker

### ISSUE THREAD

**Issue by parabool** [OmertaBeyond/OBv2#73]
Sometimes when playing slots (10k) the loss is counted as 10 dollar instead.
Profit is rightly counted as 10-20-50k.
Money lost and profit are therefore bugged.
Running Firefox on Linux Mint

**Comment by Ivdbroek85** [comment]
Tested on Firefox:
SlotsTracker
Games played:50
Games won:9 (18%)
Jackpot:0 ($0)
Triple BAR:0
Money spent:$500,000
Money won:$380,000
Profit:-$120,000

Tested on Chrome:
SlotsTracker
Games played:50
Games won:11 (22%)
Jackpot:0 ($0)
Triple BAR:0
Money spent:$500,000
Money won:$360,000
Profit:-$140,000
