### ISSUE TITLE
bust priority removes top "Bust out" button on Newmerta

### ISSUE THREAD

**Issue by Baelor** [OmertaBeyond/OBv2#91]
disabled:
![image](https://cloud.githubusercontent.com/assets/6425106/6132224/69e0315a-b151-11e4-8a2f-1b710bd1a5f3.png)
enabled:
![image](https://cloud.githubusercontent.com/assets/6425106/6132235/7b905ec0-b151-11e4-8d38-5f34e9fb7e6f.png)

**Comment by Ivdbroek85** [comment]
Did that on purpose to clean it up
