### ISSUE TITLE
Update OUJS collaboration metadata block to new format

### ISSUE THREAD

**Issue by Martii** [OmertaBeyond/OBv2#93]
Would you please resync to OUJS at your earliest convenience... there appears to be a small migration issue with `@author` being in the incorrect block... I can't reproduce it on my account with a manual update... theoretically it should self fix itself. Think the OUJS migration routine was a bit flawed... will investigate it.

TIA.
OUJS Admin

**Comment by Martii** [comment]
n/m... found out what was the issue... apologies for the noise. :) Still might want to update to the the new block though for your collaboration there. :) Close at your convenience.

**Comment by Baelor** [comment]
Just pushed a new release to the fork that syncs to OUJS (https://github.com/vBm/OBv2), hope that triggered the update/resync. Feel free to reopen if we can help in some way!

**Comment by Martii** [comment]
Thanks @Baelor.

Well... this project uses the eol'd oujs prefixed UserScript metadata block keys of:

``` javascript
// @oujs:author              vBm
// @oujs:collaborator        Gwildor
// @oujs:collaborator        MurderInc
// @oujs:collaborator        Sebbe
// @oujs:collaborator        Brainscrewer
// @oujs:collaborator        Ivdbroek85
```

... these have changed... if it is still wanted to be used for OUJS on-site collaboration use this code **outside of** the UserScript metadata block:

``` javascript
// ==OpenUserJS==
// @author              vBm
// @collaborator        Gwildor
// @collaborator        MurderInc
// @collaborator        Sebbe
// @collaborator        Brainscrewer
// @collaborator        Ivdbroek85
// ==/OpenUserJS==
```

... there is an example of this at https://openuserjs.org/user/add/scripts#collaboration e.g. we have our own block now for internals to minimize name collisions.

Historical ref #17 

---

Btw... 

> Feel free to reopen if we can help in some way!

There appears to be no reopen and comment button... don't know know exactly why.

**Comment by Baelor** [comment]
Thanks, that cleared it up for me. We'll track the format upgrade here and get it pushed with the next release!
